default = "hhuOS"
timeout = 0
log_level = "info"

[entries]
  [entries.hhuOS]
    name = "hhuOS"
    image = "\\hhuOS.bin"
    argv = "log_level=inf log_ports=COM1 root=ide1p0,Filesystem::Fat::FatDriver"